InventoryMS/InventoryMS/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

InventoryMS/dashboard/urls.py
from django.urls import path

from . import views
from .views import UserProfileView

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard_index, name='dashboard_index'),
    path('add-products/', views.add_products, name='add_products'),
    path('search-products/', views.search_available_products, name='search_available_products'),
    path('view-available-products/', views.view_available_products, name='view_available_products'),
    path('sell-available-products/', views.sell_available_products, name='sell_available_products'),
    path('view-sold-products/', views.view_sold_products, name='view_sold_products'),
    path('users/', views.users, name='users'),
    path('remove_user/', views.remove_user, name='remove_user'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('product_list/', views.product_list, name='product_list'),
    path('update_product/<int:product_id>/', views.update_product, name='update_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('shop-products/', views.shop_products, name='shop_products'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
]

InventoryMS/dashboard/models.py
from django.db import models


# Create your models here.

class Available_product_table(models.Model):
    id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=50)
    product_price = models.IntegerField()
    product_quantity = models.IntegerField()

    def __str__(self):
        return f"{self.id} - {self.product_name} - {self.product_price} - {self.product_quantity}"


class Sold_product_table(models.Model):
    date_time = models.DateTimeField(auto_now=True)
    product_id = models.IntegerField()
    product_name = models.CharField(max_length=50)
    product_price = models.IntegerField()
    product_quantity = models.IntegerField()

    def __str__(self):
        return f"{self.id} - {self.date_time} - {self.product_id} - {self.product_name} - {self.product_price} - {self.product_quantity}"

InventoryMS/dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

from .models import Available_product_table


class ProductForm(forms.ModelForm):
    class Meta:
        model = Available_product_table
        fields = ['product_name', 'product_price', 'product_quantity']


class AddProductForm(forms.ModelForm):
    product_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Product Name'}))
    product_price = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Product Price'}))
    product_quantity = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Quantity'}))

    class Meta():
        model = Available_product_table
        fields = '__all__'


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User  # Assuming you have imported User from django.contrib.auth.models
        fields = ['first_name', 'last_name', 'email']


class SearchForm(forms.Form):
    search_product = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter Product Name', 'class': 'form-control my-0 py-1'}))

InventoryMS/dashboard/views.py
# Import necessary modules and classes from Django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View

# Import models, forms, and CustomUserChangeForm from the current app
from . import models
from .forms import AddProductForm, SearchForm, CustomUserChangeForm


# Define a view function for the dashboard index
@login_required
def dashboard_index(request):
    # Retrieve user information
    user = request.user
    f_name = request.user.first_name or 'N/A'
    l_name = request.user.last_name or 'N/A'
    email = request.user.email or 'N/A'

    # Print user information for debugging (optional)
    print(user)

    if user.username == 'admin':
        # Render the admin dashboard page
        return render(request, 'dashboard/index.html',
                      {'title': 'Admin Dashboard', 'user_type': 'Admin', 'f_name': f_name, 'l_name': l_name,
                       'email': email})
    else:
        # Render the regular user dashboard page
        return render(request, 'dashboard/index-user.html',
                      {'title': 'User Dashboard', 'user_type': 'User', 'f_name': f_name, 'l_name': l_name,
                       'email': email})


# Define a view function for adding products
@login_required
def add_products(request):
    form = AddProductForm()

    if request.method == 'POST':
        # Handle form submission
        form = AddProductForm(request.POST)

        if form.is_valid():
            # Save the form if it is valid
            form.save()

            # Render the result page with success message
            context = {
                'result': 'New Product Added successfully',
                'title': 'Add Products',
            }
            return render(request, 'dashboard/result.html', context=context)
        else:
            # Render the result page with an error message
            context = {
                'result': 'ERROR',
                'title': 'Add Products',
            }
            return render(request, 'dashboard/result.html', context=context)

    # Render the form for adding products
    context = {
        'form': form,
        'title': 'Add Products',
    }
    return render(request, 'dashboard/add_product.html', context=context)


# Define a view function for searching available products
@login_required
def search_available_products(request):
    form = SearchForm()

    if request.method == 'POST':
        # Handle form submission
        form = SearchForm(request.POST)

        if form.is_valid():
            # Retrieve search_product from the form
            search_product = form.cleaned_data['search_product']

            # Query the database for products with matching names
            all_products = models.Available_product_table.objects.filter(product_name=search_product).values()

            # Render the result page with the list of matching products
            context = {
                'all_products': all_products,
                'title': 'Search Result',
            }
            return render(request, 'dashboard/view_available_products.html', context=context)

    # Render the form for searching available products
    context = {
        'form': form,
        'title': 'Search Products',
    }
    return render(request, 'dashboard/search_product.html', context=context)


# Define a view function for viewing all available products
@login_required
def view_available_products(request):
    # Query the database for all available products
    all_products = models.Available_product_table.objects.all()

    # Render the page with the list of all available products
    context = {
        'all_products': all_products,
        'title': 'All Products',
    }
    return render(request, 'dashboard/view_available_products.html', context=context)


# Define a view function for selling available products
@login_required
def sell_available_products(request):
    if request.method == 'POST':
        # Handle form submission
        sell_product_id = request.POST['product_id']
        sell_qty = int(request.POST['sellqty'])

        # Query the database for the selected product
        sell_product = models.Available_product_table.objects.filter(id=sell_product_id).values()
        sell_product = sell_product[0]

        if sell_qty <= sell_product['product_quantity']:
            # Create a Sold_product_table entry for the sold product
            product = models.Sold_product_table(
                product_id=sell_product['id'],
                product_name=sell_product['product_name'],
                product_price=sell_product['product_price'],
                product_quantity=sell_qty,
            )
            product.save()

            # Update the Available_product_table with the remaining quantity
            remaning_qty = sell_product['product_quantity'] - sell_qty
            update_product = models.Available_product_table.objects.get(id=sell_product_id)
            update_product.product_quantity = remaning_qty
            update_product.save()

            # Render the result page with success message
            context = {
                'result': 'Product sold successfully!',
                'title': 'Buy Products',
            }
            return render(request, 'dashboard/result.html', context=context)
        else:
            # Render the result page with an error message
            context = {
                'result': 'Enter Quantity is less than available stock or Product is Out of Stock!',
                'title': 'Buy Products',
            }
            return render(request, 'dashboard/result.html', context=context)

    # Query the database for all available products
    all_products = models.Available_product_table.objects.all()

    # Render the form for selling available products
    context = {
        'all_products': all_products,
        'title': 'Buy Products',
    }
    return render(request, 'dashboard/buy_products.html', context=context)


# Define a view function for viewing sold products
@login_required
def view_sold_products(request):
    # Query the database for all sold products
    all_sold_products = models.Sold_product_table.objects.all()

    # Render the page with the list of all sold products
    context = {
        'all_sold_products': all_sold_products,
        'title': 'Sold Products',
    }
    return render(request, 'dashboard/view_sold_products.html', context=context)


# Define a view function for managing users
@login_required
def users(request):
    # Create a UserCreationForm instance
    form = UserCreationForm

    if request.method == 'POST':
        # Handle form submission
        form = UserCreationForm(request.POST)

        if form.is_valid():
            # Save the form if it is valid
            form.save()

            # Render the result page with success message
            context = {
                'result': 'User Added successfully',
                'title': 'Add User',
            }
            return render(request, 'dashboard/result.html', context=context)
        else:
            # Render the result page with an error message
            context = {
                'result': 'ERROR - Does not meet the requirements!',
                'title': 'Add User',
            }
            return render(request, 'dashboard/result.html', context=context)

    # Render the form for adding users
    context = {
        'form': form,
        'title': 'Add User',
    }
    return render(request, 'dashboard/user.html', context=context)


# Define a view function for removing users
@login_required
def remove_user(request):
    # Query the database for all users
    users = User.objects.all()

    # Render the page for removing users
    return render(request, 'dashboard/remove_user.html', {'users': users, 'title': 'Remove User'})


# Define a view function for deleting a user
@login_required
def delete_user(request, user_id):
    # Retrieve the user by ID
    u_id = User.objects.get(pk=user_id)

    # Check if the request is a POST request (i.e., form submission)
    if request.method == 'POST':
        # Perform user removal
        if u_id.is_superuser:
            # You may want to handle this case differently, e.g., display an error message
            return render(request, 'dashboard/result.html',
                          {'title': 'Remove User', 'result': 'Cannot delete the admin user.'})
        u_id.delete()

    # Redirect to the dashboard index page after user deletion
    return render(request, 'dashboard/index.html')


# Define a view function for listing available products
@login_required
def product_list(request):
    # Query the database for available products with quantity greater than 0
    products = models.Available_product_table.objects.filter(product_quantity__gt=0)

    # Render the page with the list of available products
    return render(request, 'dashboard/product_list.html', {'title': 'Product List', 'products': products})


# Define a view function for updating a product
@login_required
def update_product(request, product_id):
    # Retrieve the product by ID
    product = models.Available_product_table.objects.get(pk=product_id)

    if request.method == 'POST':
        # Update the product fields directly
        product.product_name = request.POST['product_name']
        product.product_price = request.POST['product_price']
        product.product_quantity = request.POST['product_quantity']
        product.save()

        # Redirect to the product list page after product update
        return redirect('dashboard:product_list')

    # Render the form for updating a product
    return render(request, 'dashboard/update_product.html', {'title': 'Update Product', 'product': product})

InventoryMS/dashboard/templates/dashboard/add_product.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}


    <div class="user-list-card">
        <form method="POST">
            {% csrf_token %}

            <div class="form-group mx-4 mt-4">
                {{ form.as_p }}
            </div>

            <div class="form-group mx-4 mt-4">
                <button type="submit" class="btn login-btn btn-block ">Add Product</button>
            </div>
        </form>
    </div>

{% endblock %}

InventoryMS/dashboard/templates/dashboard/base.html
{% extends 'base.html' %}
{% block content %}

    <div class="container h-100">
        <div class="row align-items-center h-100">

            <div class="col-9 mx-auto">

                <div class="content-card mt-4" style="margin: 10px;padding: 5px">
                    <div class="text-center p-1">
                        <h3 class="theme-color center-heading pad-five">{{ title }}</h3>
                    </div>
                </div>

                {% block dashboardcontent %}

                {% endblock %}

            </div>
        </div>
    </div>


{% endblock %}

InventoryMS/dashboard/templates/dashboard/buy_products.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}
    <div class="content-card mx-auto">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group mx-4 mt-4">
                <select name='product_id' class="form-control" required>
                    <option value="" disabled selected hidden>-- Select Product --</option>
                    {% if all_products.count > 0 %}

                        {% for item in all_products %}
                            <option value={{ item.id }}>Product id: {{ item.id }} - {{ item.product_name }}</option>
                        {% endfor %}

                    {% endif %}
                </select>
            </div>

            <div class="form-group mx-4 mt-4">
                <input type="number" required name="sellqty" class="form-control" placeholder="Quantity" min="1">
            </div>

            <div class="form-group mx-4 mt-4">
                <button type="submit" class="btn login-btn btn-block ">Buy Product</button>
            </div>
        </form>
    </div>
{% endblock %}

InventoryMS/dashboard/templates/dashboard/index-user.html
{% extends 'base.html' %}
{% block content %}
    <div class="user-list-card" style="max-width: 1200px; margin: auto;">
        <table>
            <tr>
                <td><strong>First Name</strong></td>
                <td>{{ f_name }}</td>
            </tr>
            <tr>
                <td><strong>Last Name</strong></td>
                <td>{{ l_name }}</td>
            </tr>
            <tr>
                <td><strong>Email</strong></td>
                <td>{{ email }}</td>
            </tr>
        </table>
        <div class="mt-4">
            <div class="text-center p-3">
                <h2 class="theme-color">User Dashboard</h2>
            </div>
        </div>

        <div class="container">
            <div class="row my-4">
                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3"
                            onclick="location.href='{% url 'dashboard:search_available_products' %}'">
                        <i class="fa-solid fa-user" style="color: #ffffff;"></i> Search Products
                    </button>
                </div>

                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3"
                            onclick="location.href='{% url 'dashboard:shop_products' %}'">
                        <i class="fas fa-boxes pr-3"></i> Shop
                    </button>
                </div>
                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3"
                            onclick="location.href='{% url 'dashboard:view_sold_products' %}'">
                        <i class="fas fa-boxes pr-3"></i> Recently Sold
                    </button>
                </div>
                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3"
                            onclick="location.href='{% url 'dashboard:user_profile' %}'">
                        <i class="fas fa-boxes pr-3"></i> Profiles
                    </button>
                </div>

            </div>

        </div>
    </div>

{% endblock %}

InventoryMS/dashboard/templates/dashboard/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="user-list-card" style="max-width: 1200px; margin: auto;">
        <div class="mt-4">
            <div class="text-center p-3">
                <h2 class="theme-color">Admin Dashboard</h2>
            </div>
        </div>

        <div class="container">
            <table>

                <tr>
                    <td><strong>First Name</strong></td>
                    <td>{{ f_name }}</td>
                </tr>
                <tr>
                    <td><strong>Last Name</strong></td>
                    <td>{{ l_name }}</td>
                </tr>
                <tr>
                    <td><strong>Email</strong></td>
                    <td>{{ email }}</td>
                </tr>
            </table>
            <div class="row my-4">

                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3"
                            onclick="location.href='{% url 'dashboard:add_products' %}'">
                        <i class="fa-solid fa-pen-to-square pr-3" style="color: #ffffff;"></i> Add Products
                    </button>
                </div>

                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3"
                            onclick="location.href='{% url 'dashboard:search_available_products' %}'">
                        <i class="fas fa-search pr-3"></i> Search Products
                    </button>
                </div>

                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3"
                            onclick="location.href='{% url 'dashboard:view_available_products' %}'">
                        <i class="fa-solid fa-store pr-3" style="color: #ffffff;"></i> View All Products
                    </button>
                </div>
                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3"
                            onclick="location.href='{% url 'dashboard:user_profile' %}'">
                        <i class="fa-solid fa-user pr-3" style="color: #ffffff;"></i> Profiles
                    </button>
                </div>
            </div>

            <div class="row my-4">
                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3"
                            onclick="location.href='{% url 'dashboard:product_list' %}'">
                        <i class="fa-solid fa-gear pr-3" style="color: #ffffff;"></i> Alter Products
                    </button>
                </div>

                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3"
                            onclick="location.href='{% url 'dashboard:view_sold_products' %}'">
                        <i class="fa-solid fa-cash-register pr-3" style="color: #ffffff;"></i> View Sold Products
                    </button>
                </div>

                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:users' %}'">
                        <i class="fas fa-user-shield pr-3"></i> Users
                    </button>
                </div>
                <div class="col-sm">
                    <button class="btn btn-block action-btn p-3"
                            onclick="location.href='{% url 'dashboard:remove_user' %}'">
                        <i class="fa-solid fa-user-minus pr-3" style="color: #ffffff;"></i>
                        Remove User
                    </button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

InventoryMS/dashboard/templates/dashboard/product_list.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}
    <div class="content-card mx-auto">
        <table>
            <thead>
            <tr>
                <th>Sr no.</th>
                <th>Product ID</th>
                <th>Product Name</th>
                <th>Product Price</th>
                <th>Quantity</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ product.id }}</td>
                    <td>{{ product.product_name }}</td>
                    <td>{{ product.product_price }}</td>
                    <td>{{ product.product_quantity }}</td>
                    <td>
                        <a href="{% url 'dashboard:update_product' product.id %}" class="btn btn-warning"
                           style="color:#fff">Update</a>
                        <a href="{% url 'dashboard:delete_product' product.id %}" class="btn btn-danger">Delete</a>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

InventoryMS/dashboard/templates/dashboard/remove_user.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}


    <div class="user-list-card">
        <table>
            <thead>
            <tr>
                <th>Username</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>
                        <form method="POST" action="{% url 'dashboard:delete_user' user.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" onclick="confirmAndSubmit()" class="btn btn-danger btn-sm">Remove
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        function confirmAndSubmit() {
            if (confirm('Are you sure you want to remove this user?')) {
                document.getElementById('removeUserForm').submit();
            }
        }
    </script>
{% endblock %}

InventoryMS/dashboard/templates/dashboard/result.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}
    <div class="content-card mx-auto">
        <h3 class='text-center m-4'>{{ result }}</h3>

        <button class='btn action-btn btn-block' onclick="location.href={% url 'dashboard:dashboard_index' %}">Go Back
        </button>
    </div>
{% endblock %}

InventoryMS/dashboard/templates/dashboard/search_product.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}
    <div class="content-card mx-auto">
        <form method="POST">
            <div class="input-group md-form form-md form-2 p-3">
                {{ form.search_product }}
                {% csrf_token %}

                <button class="btn my-0 py-1" type="submit">
                <span class="input-group-text search-btn" id="basic-text1">
                    <i class="fas fa-search fa-fw search-icon" aria-hidden="true"></i>
                </span>
                </button>

            </div>
        </form>
    </div>
{% endblock %}

InventoryMS/dashboard/templates/dashboard/shop_products.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}
    {% load static %}
    <style>
        /* styles.css */
        #searchInput {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
        }

        .card {
            border: 1px solid #ddd;
            border-radius: 8px;
            transition: transform 0.2s;
        }

        .card:hover {
            transform: scale(1.05);
        }

        .card-img-top {
            object-fit: cover;
            height: 200px;
            border-top-left-radius: 8px;
            border-top-right-radius: 8px;
        }

        .card-body {
            text-align: center;
        }

        .buy-button {
            background-color: #28a745;
            color: white;
            cursor: pointer;
        }

        /* Simple Modal Styles */
        #buyModal {
            display: none;
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            z-index: 1000;
        }

        #buyModalOverlay {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.5);
            z-index: 999;
        }
    </style>

    <div class="content-card mx-auto">
        <!-- Product grid -->
        <div class="row" id="productGrid">
            {% for product in products %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{% static 'img/placeholder-image.jpg' %}" class="card-img-top" alt="Product Image">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.product_name }}</h5>
                            <p class="card-text">Price: ${{ product.product_price }}</p>
                            <p class="card-text">Quantity: {{ product.product_quantity }}</p>
                            <button class="btn btn-success buy-button" onclick="showModal('buyModal')">Buy</button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Simple Modal -->
    <div id="buyModal">
        <p>Future Scope: This feature is part of our future development plans</p>
        <button onclick="hideModal('buyModal')">Close</button>
    </div>

    <div id="buyModalOverlay" onclick="hideModal('buyModal')"></div>

    <script>
        function showModal(modalId) {
            document.getElementById(modalId).style.display = 'block';
            document.getElementById('buyModalOverlay').style.display = 'block';
        }

        function hideModal(modalId) {
            document.getElementById(modalId).style.display = 'none';
            document.getElementById('buyModalOverlay').style.display = 'none';
        }
    </script>

{% endblock %}

InventoryMS/dashboard/templates/dashboard/update_product.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}
    <div class="content-card mx-auto">
        <form method="POST">
            {% csrf_token %}
            <div>
                <label for="product_name">Product Name:</label>
                <input type="text" id="product_name" name="product_name" value="{{ product.product_name }}">
            </div>
            <div>
                <label for="product_price">Product Price:</label>
                <input type="text" id="product_price" name="product_price" value="{{ product.product_price }}">
            </div>
            <div>
                <label for="quantity">Quantity:</label>
                <input type="text" id="quantity" name="product_quantity" value="{{ product.product_quantity }}">
            </div>
            <button type="submit">Update Product</button>
        </form>
    </div>
{% endblock %}

InventoryMS/dashboard/templates/dashboard/user_list.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    <h1>User List</h1>

    {% for user in user_list %}
        <div>
            <span>{{ user.username }}</span>
            <!-- Add other user information if needed -->
        </div>
    {% endfor %}

{% endblock %}

InventoryMS/dashboard/templates/dashboard/view_sold_products.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    {% if all_sold_products.count > 0 %}
        <div class="content-card mx-auto">
        <table class='table table-striped pad-five'>
            <thead>
            <tr>
                <th scope='col'>Date Time</th>
                <th scope='col'>Product ID</th>
                <th scope='col'>Product Name</th>
                <th scope='col'>Product Price</th>
                <th scope='col'>Quantity</th>
            </tr>
            </thead>

            <tbody>
            {% for item in all_sold_products %}
                <tr>
                    <td scope='row'>{{ item.date_time }}</th>
                    <td scope='row'>{{ item.product_id }}</th>
                    <td scope='row'>{{ item.product_name }}</td>
                    <td scope='row'>{{ item.product_price }}</td>
                    <td scope='row'>{{ item.product_quantity }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% else %}
        <h1 class='text-center'>No Products are thier to view....</h1>

    {% endif %}

<button class='btn action-btn btn-block' onclick="location.href={% url 'dashboard:dashboard_index' %}">Go Back</button>
</div>

{% endblock %}